(function () {
    window.ShaderPlaygroundExamples = {
        plasma: [
            "uniform float u_time;",
            "uniform vec2 u_resolution;",
            "uniform float u_scale;",
            "uniform float u_speed;",
            "",
            "void main() {",
            "    vec2 uv = gl_FragCoord.xy / u_resolution.xy;",
            "    vec3 color = 0.5 + 0.5 * cos(u_time * u_speed + uv.xyx * (u_scale * 6.28318) + vec3(0.0, 2.0, 4.0));",
            "    gl_FragColor = vec4(color, 1.0);",
            "}"
        ].join("\n"),

    

        waves: [
            "uniform float u_time;",
            "uniform vec2 u_resolution;",
            "uniform float u_scale;",
            "uniform float u_speed;",
            "",
            "void main() {",
            "    vec2 uv = gl_FragCoord.xy / u_resolution.xy;",
            "    vec2 centered = uv - 0.5;",
            "    centered.x *= u_resolution.x / max(u_resolution.y, 1.0);",
            "",
            "    float waveA = sin((centered.x * 8.0 * u_scale) + u_time * u_speed * 1.2);",
            "    float waveB = cos((centered.y * 10.0 * u_scale) - u_time * u_speed * 1.5);",
            "    float wave = waveA + waveB;",
            "",
            "    vec3 deep = vec3(0.03, 0.1, 0.25);",
            "    vec3 shallow = vec3(0.2, 0.7, 0.9);",
            "    float blend = 0.5 + 0.5 * sin(wave * 1.7);",
            "    vec3 color = mix(deep, shallow, blend);",
            "",
            "    gl_FragColor = vec4(color, 1.0);",
            "}"
        ].join("\n"),

        fractal: [
            "uniform float u_time;",
            "uniform vec2 u_resolution;",
            "uniform float u_scale;",
            "uniform float u_speed;",
            "",
            "void main() {",
            "    vec2 uv = gl_FragCoord.xy / u_resolution.xy;",
            "    vec2 c = (uv - 0.5) * (2.4 / max(u_scale, 0.2));",
            "    c.x *= u_resolution.x / max(u_resolution.y, 1.0);",
            "",
            "    vec2 z = vec2(0.0);",
            "    float iter = 0.0;",
            "    float maxIter = 48.0;",
            "",
            "    for (float i = 0.0; i < 48.0; i += 1.0) {",
            "        z = vec2(z.x * z.x - z.y * z.y, 2.0 * z.x * z.y) + c + vec2(0.15 * sin(u_time * u_speed * 0.25), 0.0);",
            "        if (dot(z, z) > 4.0) {",
            "            iter = i;",
            "            break;",
            "        }",
            "        iter = i;",
            "    }",
            "",
            "    float t = iter / maxIter;",
            "    vec3 color = 0.5 + 0.5 * cos(6.28318 * (vec3(0.0, 0.2, 0.4) + t + u_time * 0.03 * u_speed));",
            "    if (iter >= maxIter - 1.0) {",
            "        color = vec3(0.0, 0.02, 0.05);",
            "    }",
            "",
            "    gl_FragColor = vec4(color, 1.0);",
            "}"
        ].join("\n"),

        dithering: [
            "uniform float u_time;",
            "uniform vec2 u_resolution;",
            "uniform float u_scale;",
            "uniform float u_speed;",
            "",
            "// GLSL does not allow non-constant array indices, so i had to select",
            "// the Bayer row with if/else and the column with a dot-product mask.",
            "float bayer4x4(vec2 p) {",
            "    float x = mod(floor(p.x), 4.0);",
            "    float y = mod(floor(p.y), 4.0);",
            "",
            "    vec4 row;",
            "    if      (y < 1.0) row = vec4( 0.0,  8.0,  2.0, 10.0);",
            "    else if (y < 2.0) row = vec4(12.0,  4.0, 14.0,  6.0);",
            "    else if (y < 3.0) row = vec4( 3.0, 11.0,  1.0,  9.0);",
            "    else              row = vec4(15.0,  7.0, 13.0,  5.0);",
            "",
            "    // Build a one-hot column mask to avoid dynamic indexing.",
            "    vec4 col = vec4(",
            "        float(x < 1.0),",
            "        float(x >= 1.0 && x < 2.0),",
            "        float(x >= 2.0 && x < 3.0),",
            "        float(x >= 3.0)",
            "    );",
            "",
            "    return dot(row, col) / 16.0;",
            "}",
            "",
            "void main() {",
            "    vec2 uv = gl_FragCoord.xy / u_resolution.xy;",
            "",
            "    // Placeholder source color instead  of camera : Unity version is sampled _BlitTexture.",
            "    vec3 source = 0.5 + 0.5 * cos((u_time * u_speed) + uv.xyx * vec3(6.0, 5.0, 4.0));",
            "",
            "    float scale = u_resolution.x / (640.0 * max(u_scale, 0.2));",
            "    vec2 pixelPos = floor(uv * u_resolution.xy / scale);",
            "",
            "    float luminance = dot(source, vec3(0.299, 0.587, 0.114));",
            "    float threshold = bayer4x4(pixelPos);",
            "",
            "    float ditherStrength = 0.01 * (u_resolution.x / 1280.0);",
            "    float dithered = step(threshold, luminance + ditherStrength * (threshold - 0.5));",
            "",
            "    vec3 finalColor = mix(source, source * 0.5, dithered * 0.55);",
            "    gl_FragColor = vec4(finalColor, 1.0);",
            "}"        ].join("\n"),

        neonGlobe: [
            "// Best viewed with: Shader Mode → Sphere Shader",
            "uniform float u_time;",
            "uniform vec2 u_resolution;",
            "uniform float u_scale;",
            "uniform float u_speed;",
            "varying vec2 v_uv;",
            "",
            "void main() {",
            "    vec2 uv = v_uv;",
            "    float t = u_time * u_speed;",
            "",
            "    // Latitude and longitude grid lines on UV space.",
            "    float lat = abs(fract(uv.y * u_scale * 7.0) - 0.5);",
            "    float lon = abs(fract(uv.x * u_scale * 7.0) - 0.5);",
            "    float grid = 1.0 - step(0.04, lat) * step(0.04, lon);",
            "",
            "    // Aurora color cycling along latitude.",
            "    vec3 colorA = vec3(0.0,  0.9, 0.85);",
            "    vec3 colorB = vec3(0.75, 0.1, 0.95);",
            "    float blend = 0.5 + 0.5 * sin(t * 0.8 + uv.y * 6.28318 * 1.5);",
            "    vec3 lineColor = mix(colorA, colorB, blend);",
            "    lineColor *= 0.6 + 0.4 * sin(t * 1.7 + uv.x * 12.0);",
            "",
            "    // Dark base with subtle pole glow.",
            "    float poleGlow = pow(abs(uv.y - 0.5) * 2.0, 2.0);",
            "    vec3 base = mix(vec3(0.02, 0.04, 0.12), vec3(0.06, 0.0, 0.18), poleGlow);",
            "",
            "    vec3 color = mix(base, lineColor, grid * (0.7 + 0.3 * sin(t + uv.x * 8.0)));",
            "    gl_FragColor = vec4(color, 1.0);",
            "}"
        ].join("\n"),

        holoCube: [
            "// Best viewed with: Shader Mode → Cube Shader",
            "uniform float u_time;",
            "uniform vec2 u_resolution;",
            "uniform float u_scale;",
            "uniform float u_speed;",
            "varying vec2 v_uv;",
            "",
            "void main() {",
            "    vec2 uv = v_uv;",
            "    float t = u_time * u_speed;",
            "",
            "    // Edge glow — brightest where UV approaches 0 or 1.",
            "    vec2 edgeDist = min(uv, 1.0 - uv);",
            "    float edge = clamp(1.0 - min(edgeDist.x, edgeDist.y) * 8.0 * u_scale, 0.0, 1.0);",
            "",
            "    // Diagonal scanlines sweeping across each face.",
            "    float scan = fract((uv.x + uv.y) * u_scale * 6.0 - t * 1.5);",
            "    scan = pow(1.0 - abs(scan - 0.5) * 2.0, 4.0) * 0.5;",
            "",
            "    // Radial pulse from the centre of each face.",
            "    float dist = length(uv - 0.5);",
            "    float pulse = 0.4 + 0.6 * (0.5 + 0.5 * cos(t * 2.0 - dist * 18.0 * u_scale));",
            "",
            "    // Slowly cycling hue between electric blue and magenta.",
            "    vec3 colorA = vec3(0.0, 0.55, 1.0);",
            "    vec3 colorB = vec3(0.9, 0.05, 0.8);",
            "    vec3 faceColor = mix(colorA, colorB, 0.5 + 0.5 * sin(t * 0.6));",
            "",
            "    vec3 base  = vec3(0.03, 0.04, 0.1);",
            "    vec3 lit   = faceColor * (edge + scan + pulse * 0.35);",
            "    vec3 color = mix(base, lit, 0.85);",
            "    gl_FragColor = vec4(color, 1.0);",
            "}"        ].join("\n")
    };
})();
